"""Added the modelscddds

Revision ID: 64dac8afca70
Revises: e552ec52061e
Create Date: 2024-02-18 11:23:14.260337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dac8afca70'
down_revision = 'e552ec52061e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=20), nullable=True))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATETIME(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
